// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAYuomUyxlKO5GVD1LaUEoY3LaoNH3Xxs',
    appId: '1:684691448025:web:e044624c3c77f24da51ec8',
    messagingSenderId: '684691448025',
    projectId: 'kneexpert-sales-app',
    authDomain: 'kneexpert-sales-app.firebaseapp.com',
    storageBucket: 'kneexpert-sales-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmU-FvyyeaZ1UHtggib8RYGtteLaT_G4w',
    appId: '1:684691448025:android:679417ce46b94b1aa51ec8',
    messagingSenderId: '684691448025',
    projectId: 'kneexpert-sales-app',
    storageBucket: 'kneexpert-sales-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCttEIenOVjCCLqjA9o1GupeQJPtnN87to',
    appId: '1:684691448025:ios:140ae6125f787372a51ec8',
    messagingSenderId: '684691448025',
    projectId: 'kneexpert-sales-app',
    storageBucket: 'kneexpert-sales-app.firebasestorage.app',
    iosBundleId: 'com.kneexpert.kneexpertreport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCttEIenOVjCCLqjA9o1GupeQJPtnN87to',
    appId: '1:684691448025:ios:140ae6125f787372a51ec8',
    messagingSenderId: '684691448025',
    projectId: 'kneexpert-sales-app',
    storageBucket: 'kneexpert-sales-app.firebasestorage.app',
    iosBundleId: 'com.kneexpert.kneexpertreport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAYuomUyxlKO5GVD1LaUEoY3LaoNH3Xxs',
    appId: '1:684691448025:web:aa0a3ad7e4830a3da51ec8',
    messagingSenderId: '684691448025',
    projectId: 'kneexpert-sales-app',
    authDomain: 'kneexpert-sales-app.firebaseapp.com',
    storageBucket: 'kneexpert-sales-app.firebasestorage.app',
  );

}