// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa2weYvfjDNQJBuDaA-Uapm7OV7gs_Atk',
    appId: '1:160927937376:web:fc5e70daa35f7b2fd22405',
    messagingSenderId: '160927937376',
    projectId: 'kneexpert-report',
    authDomain: 'kneexpert-report.firebaseapp.com',
    storageBucket: 'kneexpert-report.firebasestorage.app',
    measurementId: 'G-1XX08C9EG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS6wCq-f5hfGRYnDu3uqnzzfZFxg8GO2U',
    appId: '1:160927937376:android:1c6fc0973d2bfa49d22405',
    messagingSenderId: '160927937376',
    projectId: 'kneexpert-report',
    storageBucket: 'kneexpert-report.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd2rAlurL6fIIbcU2DLCsvRLvopnP2sjs',
    appId: '1:160927937376:ios:4c0da460e638928dd22405',
    messagingSenderId: '160927937376',
    projectId: 'kneexpert-report',
    storageBucket: 'kneexpert-report.firebasestorage.app',
    iosBundleId: 'com.kneexpert.kneexpertreport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd2rAlurL6fIIbcU2DLCsvRLvopnP2sjs',
    appId: '1:160927937376:ios:4c0da460e638928dd22405',
    messagingSenderId: '160927937376',
    projectId: 'kneexpert-report',
    storageBucket: 'kneexpert-report.firebasestorage.app',
    iosBundleId: 'com.kneexpert.kneexpertreport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa2weYvfjDNQJBuDaA-Uapm7OV7gs_Atk',
    appId: '1:160927937376:web:c7f98baa3f50aef4d22405',
    messagingSenderId: '160927937376',
    projectId: 'kneexpert-report',
    authDomain: 'kneexpert-report.firebaseapp.com',
    storageBucket: 'kneexpert-report.firebasestorage.app',
    measurementId: 'G-DG3YKDZF7H',
  );
}
